#!/bin/bash
TARGET_DIR="$HOME/Applications/veil"


mkdir -p "$TARGET_DIR"


README_FILE="$TARGET_DIR/README"

echo "Application Created!"
sleep 4

echo "App should be in the \"veil\" folder." > "$README_FILE"
