#!/bin/bash
echo "Welcome, $(whoami)...."
sleep 10
echo "Please wait..."
sleep 6
echo "Loading."
sleep 1
echo "Loading.."
sleep 1
echo "Loading..."
sleep 1
echo "Loading...."
sleep 1
echo "Loading..."
sleep 1
echo "Loading...."
sleep 1
echo "Loading....."
sleep 1
echo "Loading."
sleep 1
echo "Loading.."
sleep 1
echo "Loading..."
sleep 1
echo "Loading...."
sleep 1
echo "Loading....."
sleep 1
echo "Loading."
sleep 1
echo "Loading.."
sleep 4 
echo "Loaded!"
sleep 4

read -p "Enter License Key: " license_key

if [ "$license_key" == "12851" ]; then
    echo "License key accepted. Downloading file..."

DESTINATION_PATH="/Applications/$veil"

# Create the folder
sudo mkdir -p "$DESTINATION_PATH"


    # Define the raw URL of the file to be downloaded from GitHub
    FILE_URL="https://raw.githubusercontent.com/Sadospry/veil/blob/main/download"
    
    # Define the destination path for the downloaded file
DESTINATION_PATH=" /Applications/veil"
# Download the file using curl
    curl -L -o "$DESTINATION_PATH" "$FILE_URL"
    
    # Check if the download was successful
    if [ $? -eq 0 ]; then
RGB_COLOR="\033[38;2;0;255;0m"
# Print the message in fully green color
echo -e "${RGB_COLOR}File downloaded successfully to $DESTINATION_PATH.\033[0m"
    else
        RGB_COLOR="\033[38;2;255;0;0m"  # Red color
        echo -e "${RGB_COLOR}File failed to download.\033[0m"
        exit 12851
    fi
else
    echo "Invalid license key."
    exit 12851
fi
