#!/bin/bash
echo "Welcome, $(whoami)...."
sleep 10
echo "Please wait..."
sleep 6
echo "Loading."
sleep 1
echo "Loading.."
sleep 1
echo "Loading..."
sleep 1
echo "Loading...."
sleep 1
echo "Loading....."
sleep 1
echo "Loading."
sleep 1
echo "Loading.."
sleep 1
echo "Loading..."
sleep 1
echo "Loading...."
sleep 1
echo "Loading....."
sleep 1
echo "Loading."
sleep 1
echo "Loading.."
sleep 1
echo "Loading..."
sleep 1
echo "Loading...."
sleep 2
echo "Loaded!"
sleep 4

read -p "Enter License Key: " license_key

if [ "$license_key" == "12851" ]; then
    echo "License key accepted. Downloading file..."

target_directory="$HOME/Applications/veil"
filename="README.txt"
file_path="$target_directory/$filename"

# Create the target directory if it doesn't exist
mkdir -p "$target_directory"

# Create the README file with some content
cat <<EOL > "$file_path"
# README

App should be in $(whoami)/Applications/veil
EOL

    if [ $? -eq 0 ]; then
RGB_COLOR="\033[38;2;0;255;0m"
# Print the message in fully green color
echo -e "${RGB_COLOR}File downloaded successfully to $DESTINATION_PATH.\033[0m"
    else
        RGB_COLOR="\033[38;2;255;0;0m"  # Red color
        echo -e "${RGB_COLOR}File failed to download.\033[0m"
        exit 12851
    fi
else
    echo "Invalid license key."
    exit 12851
fi
